export const AGENT_CREATE_REQUEST = "AGENT_CREATE_REQUEST";
export const AGENT_CREATE_SUCCESS = "AGENT_CREATE_SUCCESS";
export const AGENT_CREATE_FAIL = "AGENT_CREATE_FAIL";

export const AGENT_LIST_REQUEST = "AGENT_LIST_REQUEST";
export const AGENT_LIST_SUCCESS = "AGENT_LIST_SUCCESS";
export const AGENT_LIST_FAIL = "AGENT_LIST_FAIL";

export const STATE_LIST_REQUEST = "STATE_LIST_REQUEST";
export const STATE_LIST_SUCCESS = "STATE_LIST_SUCCESS";
export const STATE_LIST_FAIL = "STATE_LIST_FAIL";

export const CITY_LIST_REQUEST = "CITY_LIST_REQUEST";
export const CITY_LIST_SUCCESS = "CITY_LIST_SUCCESS";
export const CITY_LIST_FAIL = "CITY_LIST_FAIL";

export const AGENT_DELETE_REQUEST = "AGENT_DELETE_REQUEST";
export const AGENT_DELETE_SUCCESS = "AGENT_DELETE_SUCCESS";
export const AGENT_DELETE_FAIL = "AGENT_DELETE_FAIL";