export const DEALER_LIST_REQUEST = "DEALER_LIST_REQUEST";
export const DEALER_LIST_SUCCESS = "DEALER_LIST_SUCCESS";
export const DEALER_LIST_FAIL = "DEALER_LIST_FAIL";

export const DEALER_BOOK_LIST_REQUEST = "DEALER_BOOK_LIST_REQUEST";
export const DEALER_BOOK_LIST_SUCCESS = "DEALER_BOOK_LIST_SUCCESS";
export const DEALER_BOOK_LIST_FAIL = "DEALER_BOOK_LIST_FAIL";

export const DEALER_DETAIL_REQUEST = "DEALER_DETAIL_REQUEST";
export const DEALER_DETAIL_SUCCESS = "DEALER_DETAIL_SUCCESS";
export const DEALER_DETAIL_FAIL = "DEALER_DETAIL_FAIL";

export const ADD_DEALER_REQUEST = "ADD_DEALER_REQUEST";
export const ADD_DEALER_SUCCESS = "ADD_DEALER_SUCCESS";
export const ADD_DEALER_FAIL = "ADD_DEALER_FAIL";
export const DEALER_RESET = "DEALER_RESET";

export const ADD_BOOK_REQUEST = "ADD_BOOK_REQUEST";
export const ADD_BOOK_SUCCESS = "ADD_BOOK_SUCCESS";
export const ADD_BOOK_FAIL = "ADD_BOOK_FAIL";
export const ADD_BOOK_RESET = "ADD_BOOK_RESET";
export const ADD_BOOK_RESET_ERROR = "ADD_BOOK_RESET_ERROR";