export const DEALER_LIST_REQUEST = "DEALER_LIST_REQUEST";
export const DEALER_LIST_SUCCESS = "DEALER_LIST_SUCCESS";
export const DEALER_LIST_FAIL = "DEALER_LIST_FAIL";

export const DEALER_BOOK_LIST_REQUEST = "DEALER_BOOK_LIST_REQUEST";
export const DEALER_BOOK_LIST_SUCCESS = "DEALER_BOOK_LIST_SUCCESS";
export const DEALER_BOOK_LIST_FAIL = "DEALER_BOOK_LIST_FAIL";

export const DEALER_DETAIL_REQUEST = "DEALER_DETAIL_REQUEST";
export const DEALER_DETAIL_SUCCESS = "DEALER_DETAIL_SUCCESS";
export const DEALER_DETAIL_FAIL = "DEALER_DETAIL_FAIL";

export const ADD_DEALER_REQUEST = "ADD_DEALER_REQUEST";
export const ADD_DEALER_SUCCESS = "ADD_DEALER_SUCCESS";
export const ADD_DEALER_FAIL = "ADD_DEALER_FAIL";
export const DEALER_RESET = "DEALER_RESET";

export const ADD_BOOK_REQUEST = "ADD_BOOK_REQUEST";
export const ADD_BOOK_SUCCESS = "ADD_BOOK_SUCCESS";
export const ADD_BOOK_FAIL = "ADD_BOOK_FAIL";
export const ADD_BOOK_RESET = "ADD_BOOK_RESET";
export const ADD_BOOK_RESET_ERROR = "ADD_BOOK_RESET_ERROR";

export const BOOK_DETAIL_REQUEST = "BOOK_DETAIL_REQUEST";
export const BOOK_DETAIL_SUCCESS = "BOOK_DETAIL_SUCCESS";
export const BOOK_DETAIL_FAIL = "BOOK_DETAIL_FAIL";

export const BOOK_LIST_REQUEST = "BOOK_LIST_REQUEST";
export const BOOK_LIST_SUCCESS = "BOOK_LIST_SUCCESS";
export const BOOK_LIST_FAIL = "BOOK_LIST_FAIL";

export const ALL_BOOK_LIST_REQUEST = "ALL_BOOK_LIST_REQUEST";
export const ALL_BOOK_LIST_SUCCESS = "ALL_BOOK_LIST_SUCCESS";
export const ALL_BOOK_LIST_FAIL = "ALL_BOOK_LIST_FAIL";

export const EXPORT_EXCAL_REQUEST = "EXPORT_EXCAL_REQUEST";
export const EXPORT_EXCAL_SUCCESS = "EXPORT_EXCAL_SUCCESS";
export const EXPORT_EXCAL_FAIL = "EXPORT_EXCAL_FAIL";
export const EXPORT_EXCAL_RESET = "EXPORT_EXCAL_RESET";
export const EXPORT_EXCAL_ERROR = "EXPORT_EXCAL_ERROR";

export const RECIEPT_UPLOAD_REQUEST = "RECIEPT_UPLOAD_REQUEST";
export const RECIEPT_UPLOAD_SUCCESS = "RECIEPT_UPLOAD_SUCCESS";
export const RECIEPT_UPLOAD_FAIL = "RECIEPT_UPLOAD_FAIL";
export const RECIEPT_UPLOAD_RESET = "RECIEPT_UPLOAD_RESET";
export const RECIEPT_UPLOAD_ERROR = "RECIEPT_UPLOAD_ERROR";

export const MOVE_TO_COMPLETE_REQUEST = "MOVE_TO_COMPLETE_REQUEST";
export const MOVE_TO_COMPLETE_SUCCESS = "MOVE_TO_COMPLETE_SUCCESS";
export const MOVE_TO_COMPLETE_FAIL = "MOVE_TO_COMPLETE_FAIL";
export const MOVE_TO_COMPLETE_RESET = "MOVE_TO_COMPLETE_RESET";
export const MOVE_TO_COMPLETE_ERROR = "MOVE_TO_COMPLETE_ERROR";

export const DELETE_BOOK_REQUEST = "DELETE_BOOK_REQUEST";
export const DELETE_BOOK_SUCCESS = "DELETE_BOOK_SUCCESS";
export const DELETE_BOOK_FAIL = "DELETE_BOOK_FAIL";
export const DELETE_BOOK_RESET = "DELETE_BOOK_RESET";
export const DELETE_BOOK_RESET_ERROR = "DELETE_BOOK_RESET_ERROR";

export const DELETE_DEALER_REQUEST = "DELETE_DEALER_REQUEST";
export const DELETE_DEALER_SUCCESS = "DELETE_DEALER_SUCCESS";
export const DELETE_DEALER_FAIL = "DELETE_DEALER_FAIL";
export const DELETE_DEALER_RESET = "DELETE_DEALER_RESET";
export const DELETE_DEALER_RESET_ERROR = "DELETE_DEALER_RESET_ERROR";

export const DEALER_DETAIL_EDIT_REQUEST = "DEALER_DETAIL_EDIT_REQUEST";
export const DEALER_DETAIL_EDIT_SUCCESS = "DEALER_DETAIL_EDIT_SUCCESS";
export const DEALER_DETAIL_EDIT_FAIL = "DEALER_DETAIL_EDIT_FAIL";
export const EDIT_DEALER_RESET = "EDIT_DEALER_RESET";
export const EDIT_DEALER_RESET_ERROR = "EDIT_DEALER_RESET_ERROR";

export const BOOK_EDIT_REQUEST = "BOOK_EDIT_REQUEST";
export const BOOK_EDIT_SUCCESS = "BOOK_EDIT_SUCCESS";
export const BOOK_EDIT_FAIL = "BOOK_EDIT_FAIL";
export const BOOK_EDIT_RESET = "BOOK_EDIT_RESET";
export const BOOK_EDIT_RESET_ERROR = "BOOK_EDIT_RESET_ERROR";

