export const VEHICLE_CLASS_REQUEST = 'VEHICLE_CLASS_REQUEST';
export const VEHICLE_CLASS_SUCCESS = 'VEHICLE_CLASS_SUCCESS';
export const VEHICLE_CLASS_FAIL = 'VEHICLE_CLASS_FAIL';

export const VEHICLE_CATEGORIES_REQUEST = 'VEHICLE_CATEGORIES_REQUEST';
export const VEHICLE_CATEGORIES_SUCCESS = 'VEHICLE_CATEGORIES_SUCCESS';
export const VEHICLE_CATEGORIES_FAIL = 'VEHICLE_CATEGORIES_FAIL';

export const SERVICE_AUTHORITY_REQUEST = 'SERVICE_AUTHORITY_REQUEST';
export const SERVICE_AUTHORITY_SUCCESS = 'SERVICE_AUTHORITY_SUCCESS';
export const SERVICE_AUTHORITY_FAIL = 'SERVICE_AUTHORITY_FAIL';

export const INSURANCE_COMPANY_NAME_REQUEST = 'INSURANCE_COMPANY_NAME_REQUEST';
export const INSURANCE_COMPANY_NAME_SUCCESS = 'INSURANCE_COMPANY_NAME_SUCCESS';
export const INSURANCE_COMPANY_NAME_FAIL = 'INSURANCE_COMPANY_NAME_FAIL';

export const DEALER_LIST_DROPDOWN_REQUEST = 'DEALER_LIST_DROPDOWN_REQUEST';
export const DEALER_LIST_DROPDOWN_SUCCESS = 'DEALER_LIST_DROPDOWN_SUCCESS';
export const DEALER_LIST_DROPDOWN_FAIL = 'DEALER_LIST_DROPDOWN_FAIL';